import { D2Coding, firaCode, pretendard } from '@/styles/fonts';
import type { Metadata } from 'next';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${pretendard.variable} ${firaCode.variable} ${D2Coding.variable} font-body`}>
        {children}
      </body>
    </html>
  );
}
